services:
  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - mqtt_network
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log