services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - 1883:1883
    depends_on:
      - mqtt_adapter_network
    networks:
      - mqtt_adapter_network
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  
  db:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    depends_on:
      - adapter_db_network
      - grafana_db_network
    networks:
      - adapter_db_network
      - grafana_db_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - grafana_db_network
    networks:
      - grafana_db_network

  adapter:
    image: tema3scd_adapter
    container_name: adapter
    depends_on:
      - mqtt_adapter_network
      - adapter_db_network
    networks:
      - mqtt_adapter_network
      - adapter_db_network

networks:
  mqtt_adapter_network:
  adapter_db_network:
  grafana_db_network: