services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - 1883:1883
    networks:
      - mqtt_server_network
  
  db:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - server_db_network
      - grafana_bd_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - grafana_bd_network

  server:
    build: .
    container_name: server
    depends_on:
      - db
      - mqtt_broker
    networks:
      - mqtt_server_network
      - server_db_network

networks:
  mqtt_db_network:
  server_db_network:
  grafana_bd_network: