services:
  mqtt_broker:
    image: eclipse-mosquitto
    hostname: mqtt_broker
    ports:
      - 1883:1883
    depends_on:
      - mqtt_adapter_network
    networks:
      - mqtt_adapter_network
    volumes:
      - ./mosquitto-data:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  
  influxdb:
    image: influxdb:1.8
    hostname: influxdb
    depends_on:
      - adapter_db_network
      - grafana_db_network
    networks:
      - adapter_db_network
      - grafana_db_network
    volumes:
      - ./influxdb-data:/var/lib/influxdb
      - ./influxdb-config:/etc/influxdb

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - 3000:80
    depends_on:
      - grafana_db_network
    networks:
      - grafana_db_network

  adapter:
    image: tema3scd_adapter
    hostname: adapter
    depends_on:
      - mqtt_adapter_network
      - adapter_db_network
      - mqtt_broker
      - influxdb
    networks:
      - mqtt_adapter_network
      - adapter_db_network

networks:
  mqtt_adapter_network:
  adapter_db_network:
  grafana_db_network:

volumes:
  mosquitto-data:
  influxdb2-data:
  influxdb2-config: